FROM python:3.13-alpine AS base

COPY --from=ghcr.io/astral-sh/uv:0.7.2 /uv /bin/uv

WORKDIR /app

COPY uv.lock pyproject.toml /app/
RUN uv sync --frozen --no-dev
ADD conmotion /app/

ENTRYPOINT python3 -m rp
