architecture-beta
    group provider(cloud)[Cloud Infrastructure Provider]

    service provider_storage(disk)[Storage Service] in provider
    service provider_tscore(server)[Transparency Service] in provider
    service provider_search(server)[Search Service] in provider
    service provider_rp(server)[Relying Party Client] in provider

    provider_tscore:T -- L:provider_storage
    provider_tscore:L -- R:provider_search
    provider_tscore:T -- L:provider_rp
