architecture-beta
    group provider(cloud)[Transparency Service Operator]

    service provider_storage(disk)[Storage Service] in provider
    service provider_tscore(server)[Transparency Service] in provider
    service provider_search(server)[Search Service] in provider
    service provider_rp(server)[Relying Party Client] in provider

    provider_storage:L -- R:provider_search
    provider_tscore:R -- L:provider_rp
    provider_storage:L -- R:provider_rp
    provider_search:R -- R:provider_rp
