name: CD

on:
  push:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-24.04
    steps:
      - id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          submodules: true
      - id: build
        name: Build website
        uses: docker://pandoc/core:3.5
        with:
          args: |
            docs/architecture.md -o docs/architecture.html --bibliography docs/references.bib --citeproc --csl vendor/csl/apa-6th-edition.csl
      - id: publish
        name: Copy built site to stage for publication
        run: make publish          
      - id: upload
        name: Upload Build Artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          path: build

  deploy_prod:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
  
  deploy_qa:
    name: Deploy to Netlify
    if: github.ref != 'refs/heads/main'
    needs: build
    permissions:
      deployments: write
    environment:
      name: netlify
    runs-on: ubuntu-24.04
    steps:
      - id: deployment
        name: Start deployment
        uses: bobheadxi/deployments@648679e8e4915b27893bd7dbc35cb504dc915bc8
        with:
          step: start
          env: netlify
      - id: netlify
        name: Deploy QA build to Netlify
        uses: South-Paw/action-netlify-cli@0e5db3233380b841d6e0dfd3b1eef306c6c79735
        with:
          args: deploy --json --dir './build --message '${{ github.head_ref || github.ref_name }} ${{ github.sha }}'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - id: deployment_finish
        name: Finish deployment
        uses: bobheadxi/deployments@648679e8e4915b27893bd7dbc35cb504dc915bc8
        if: always()
        with:
          env: ${{ steps.deployment.outputs.env }}
          step: finish
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ fromJson(steps.netlify.outputs.NETLIFY_OUTPUT).url }}
