name: Deploy Website

on:
  push:
    paths:
      - '.github/workflows/oci_docs.yml'
      - '.tool-versions'
      - 'Containerfile.docs'
      - 'Makefile'
      - 'package.json'
      - 'package-lock.json'
      - 'docs/**'
      - 'vendor/csl/**'

jobs:
  build:
    name: Build site
    runs-on: ubuntu-24.04
    steps:
      - id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          submodules: true
      - id: setup_node
        name: Setup NodeJS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
      - id: packages_node
        name: Install NodeJS packages
        run: npm ci
      - id: setup_chrome
        name: Install Chrome for mermaid-cli to generate diagrams
        uses: browser-actions/setup-chrome@c785b87e244131f27c9f19c1a33e2ead956ab7ce
        with:
          chrome-version: 137.0.7151.68
          install-chromedriver: true
      - id: tag
        name: Prep and tag spec before build
        run: |
          make tag
      - id: render
        name: Render assets
        run: |
          make render  MERMAID_EXE_WRAPPER="aa-exec --profile=chrome"
      - id: build
        name: Build website
        uses: docker://ghcr.io/aj-stein/pandoc/latex@latest
        with:
          entrypoint: make
          args: publish
      - id: convert
        name: Convert website to PDF
        uses: docker://ghcr.io/aj-stein/pandoc/latex@sha256:73e426028ee2b197a9f8bf0a63b50c10b361436d64165d5a0c62e7d630bc94d7
        with:
          entrypoint: make
          args: convert
      - id: upload
        name: Upload Build Artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          name: website_build
          path: build

  deploy_prod:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
        with:
          artifact_name: website_build
  
  deploy_qa:
    name: Deploy to Netlify
    if: github.ref != 'refs/heads/main'
    needs: build
    permissions:
      deployments: write
    environment:
      name: netlify
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}      
    runs-on: ubuntu-24.04
    steps:
      - id: deployment
        name: Start deployment
        uses: bobheadxi/deployments@648679e8e4915b27893bd7dbc35cb504dc915bc8
        with:
          step: start
          env: netlify
      - id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - id: setup_node
        name: Setup NodeJS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
      - id: packages_node
        name: Install NodeJS packages
        run: npm ci
      - id: download
        name: Download website build
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: website_build
          path: ${{ runner.temp }}
      - id: download_extract
        name: Extract tarball from downloaded website build
        run: |
          mkdir ${{ github.workspace }}/build
          tar -xvf ${{ runner.temp }}/artifact.tar -C ${{ github.workspace }}/build
      - id: netlify_dev
        name: Deploy QA build to Netlify (develop branch)
        if: github.ref == 'refs/heads/develop'
        run: |
          npx netlify-cli deploy \
            --dir=build \
            --message '${{ github.head_ref || github.ref_name }} ${{ github.sha }}' \
            --prod \
            --json >> deploy_output.json
          echo "deploy_url=$(jq -r '.deploy_url' deploy_output.json)" >> $GITHUB_OUTPUT
      - id: netlify_pr
        name: Deploy QA build to Netlify (PR branch)
        if: github.ref != 'refs/heads/develop'
        run: |
          npx netlify-cli deploy \
            --dir=build \
            --context=branch-deploy \
            --alias=${{ github.head_ref || github.ref_name }} \
            --message '${{ github.head_ref || github.ref_name }} ${{ github.sha }}' \
            --json >> deploy_output.json
          echo "deploy_url=$(jq -r '.deploy_url' deploy_output.json)" >> $GITHUB_OUTPUT
      - id: deployment_finish
        name: Finish deployment
        uses: bobheadxi/deployments@648679e8e4915b27893bd7dbc35cb504dc915bc8
        if: always()
        with:
          env: ${{ steps.deployment.outputs.env }}
          step: finish
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ steps.netlify_dev.outputs.deploy_url || steps.netlify_pr.outputs.deploy_url }}
